# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/g/git/Heterogeneous-OpenMP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/g/git/Heterogeneous-OpenMP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/g/git/Heterogeneous-OpenMP/CMakeFiles /home/g/git/Heterogeneous-OpenMP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/g/git/Heterogeneous-OpenMP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named heterogeneous_openmp

# Build rule for target.
heterogeneous_openmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heterogeneous_openmp
.PHONY : heterogeneous_openmp

# fast build rule for target.
heterogeneous_openmp/fast:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/build
.PHONY : heterogeneous_openmp/fast

gpu_parallel_cuda.o: gpu_parallel_cuda.cu.o

.PHONY : gpu_parallel_cuda.o

# target to build an object file
gpu_parallel_cuda.cu.o:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/gpu_parallel_cuda.cu.o
.PHONY : gpu_parallel_cuda.cu.o

gpu_parallel_cuda.i: gpu_parallel_cuda.cu.i

.PHONY : gpu_parallel_cuda.i

# target to preprocess a source file
gpu_parallel_cuda.cu.i:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/gpu_parallel_cuda.cu.i
.PHONY : gpu_parallel_cuda.cu.i

gpu_parallel_cuda.s: gpu_parallel_cuda.cu.s

.PHONY : gpu_parallel_cuda.s

# target to generate assembly for a file
gpu_parallel_cuda.cu.s:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/gpu_parallel_cuda.cu.s
.PHONY : gpu_parallel_cuda.cu.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/main.cpp.s
.PHONY : main.cpp.s

sample_class.o: sample_class.cpp.o

.PHONY : sample_class.o

# target to build an object file
sample_class.cpp.o:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/sample_class.cpp.o
.PHONY : sample_class.cpp.o

sample_class.i: sample_class.cpp.i

.PHONY : sample_class.i

# target to preprocess a source file
sample_class.cpp.i:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/sample_class.cpp.i
.PHONY : sample_class.cpp.i

sample_class.s: sample_class.cpp.s

.PHONY : sample_class.s

# target to generate assembly for a file
sample_class.cpp.s:
	$(MAKE) -f CMakeFiles/heterogeneous_openmp.dir/build.make CMakeFiles/heterogeneous_openmp.dir/sample_class.cpp.s
.PHONY : sample_class.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... heterogeneous_openmp"
	@echo "... gpu_parallel_cuda.o"
	@echo "... gpu_parallel_cuda.i"
	@echo "... gpu_parallel_cuda.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sample_class.o"
	@echo "... sample_class.i"
	@echo "... sample_class.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

